In [1]:
import cv2
import numpy as np
from PIL import Image
from keras import models
import os
import tensorflow as tf

In [2]:
current_path = 'C:\\Users\\a_sha\\Desktop\\graduation cnn'

In [3]:
checkpoint_dir = os.path.dirname(current_path)

In [4]:
model = models.load_model('CNN_Model.h5')

In [5]:
video = cv2.VideoCapture(0)
while True:
        temp = []
        _, frame = video.read()

        #Convert the captured frame into RGB
        im = Image.fromarray(frame, 'RGB')
        im = im.resize((90,90))
        img_array = np.array(im)
        img_array = img_array.reshape(1,90,90,3)
        
        
        prediction = model.predict(img_array)
        if(np.argmax(prediction) == 0 and prediction[0][np.argmax(prediction)]>0.5):
            print(prediction)
            print("warning_children")
        elif(np.argmax(prediction) == 1  and prediction[0][np.argmax(prediction)]>0.5):
            print(prediction)
            print("Turn_left")
        elif(np.argmax(prediction) == 2 and prediction[0][np.argmax(prediction)]>0.5):
            print(prediction)
            print("Turn_right")
        else:
            print('Nothing')

        cv2.imshow("Prediction", frame)
        key=cv2.waitKey(0)
        if key == ord('q'):
                break
video.release()
cv2.destroyAllWindows()

[[0.9952483  0.11702761 0.1830253 ]]
warning_children
[[0.9938991  0.12373129 0.20535415]]
warning_children
[[0.9936967  0.13001251 0.1932838 ]]
warning_children
[[0.99407566 0.12689582 0.19804946]]
warning_children
[[0.9941474  0.13193676 0.18994507]]
warning_children
[[0.994665   0.12943482 0.18610904]]
warning_children
[[0.994665   0.12943482 0.18610904]]
warning_children
[[0.99276686 0.12645578 0.21619186]]
warning_children
[[0.994601   0.12353736 0.18650186]]
warning_children
[[0.9929489  0.13477463 0.19436902]]
warning_children
[[0.99300086 0.13117221 0.20701924]]
warning_children
[[0.99300086 0.13117221 0.20701924]]
warning_children
[[0.99388385 0.12582788 0.20198545]]
warning_children
[[0.99126184 0.12953296 0.22554606]]
warning_children
[[0.99398863 0.11592898 0.20191401]]
warning_children
[[0.99461377 0.11425227 0.19048771]]
warning_children
[[0.995867   0.11673969 0.15765363]]
warning_children
[[0.995867   0.11673969 0.15765363]]
warning_children
[[0.99252653 0.10559002 0.22

[[0.99433714 0.10788253 0.20134196]]
warning_children
[[0.99383163 0.11022267 0.21516865]]
warning_children
[[0.9943129  0.11589023 0.20660484]]
warning_children
[[0.992833   0.12268025 0.22346702]]
warning_children
[[0.99360156 0.12430629 0.21263504]]
warning_children
[[0.9952675  0.1207799  0.18330601]]
warning_children
[[0.9928619  0.1284869  0.21339971]]
warning_children
[[0.99372613 0.1229113  0.20953754]]
warning_children
[[0.994282   0.12942374 0.19583046]]
warning_children
[[0.99320143 0.12692848 0.21445352]]
warning_children
[[0.99162954 0.13340327 0.22720367]]
warning_children
[[0.9918423  0.12642327 0.22035635]]
warning_children
[[0.9918423  0.12642327 0.22035635]]
warning_children
[[0.9933519  0.12412184 0.19826028]]
warning_children
[[0.9926218  0.12212303 0.21562025]]
warning_children
[[0.9944134  0.12129766 0.18597654]]
warning_children
[[0.99197507 0.12665197 0.21358413]]
warning_children
[[0.99453855 0.12256825 0.18346086]]
warning_children
[[0.99277997 0.12256429 0.20

[[0.00898355 0.06151712 0.9990656 ]]
Turn_right
[[0.137642   0.106024   0.95228076]]
Turn_right
[[0.137642   0.106024   0.95228076]]
Turn_right
[[0.9020731  0.06637046 0.40662616]]
warning_children
[[0.86817753 0.03115764 0.6772724 ]]
warning_children
[[0.48841712 0.02752158 0.872985  ]]
Turn_right
[[0.48841712 0.02752158 0.872985  ]]
Turn_right
[[0.6514445  0.03405574 0.85150546]]
Turn_right
[[0.69061834 0.03636035 0.8440731 ]]
Turn_right
[[0.7196455  0.04496628 0.8142431 ]]
Turn_right
[[0.74435747 0.05162266 0.7847308 ]]
Turn_right
[[0.8129395  0.05780503 0.7019793 ]]
warning_children
[[0.8129395  0.05780503 0.7019793 ]]
warning_children
[[0.8476443  0.06166363 0.65531003]]
warning_children
[[0.8066256 0.0550285 0.7292219]]
warning_children
[[0.44624856 0.02501091 0.92285246]]
Turn_right
[[0.44624856 0.02501091 0.92285246]]
Turn_right
[[0.97065353 0.08248952 0.14296713]]
warning_children
[[0.14782181 0.021303   0.98177814]]
Turn_right
[[0.06593361 0.01315895 0.99842197]]
Turn_right
[

[[0.9778628  0.08341938 0.33719066]]
warning_children
[[0.97782844 0.08043125 0.34545025]]
warning_children
[[0.9895638  0.06715131 0.24796346]]
warning_children
[[0.9895638  0.06715131 0.24796346]]
warning_children
[[0.990028   0.07086337 0.24179551]]
warning_children
[[0.98793244 0.07275268 0.25502574]]
warning_children
[[0.9916691  0.08466634 0.19498146]]
warning_children
[[0.9916691  0.08466634 0.19498146]]
warning_children
[[0.9967145  0.08176386 0.1186116 ]]
warning_children
[[0.9470342  0.1484955  0.37764904]]
warning_children
[[0.16449863 0.05564934 0.96896464]]
Turn_right
[[0.02477175 0.0170874  0.99947786]]
Turn_right
[[0.02477175 0.0170874  0.99947786]]
Turn_right
[[0.00807282 0.30770928 0.996961  ]]
Turn_right
[[0.00353423 0.95218563 0.9833088 ]]
Turn_right
[[0.00607553 0.82723427 0.982533  ]]
Turn_right
[[0.00148302 0.8930471  0.99131715]]
Turn_right
[[0.00148302 0.8930471  0.99131715]]
Turn_right
[[6.134510e-04 9.497173e-01 9.813819e-01]]
Turn_right
[[0.00151139 0.9394958

[[0.00632104 0.564779   0.99570763]]
Turn_right
[[0.00595045 0.5076444  0.99659103]]
Turn_right
[[0.00713515 0.43874276 0.99574727]]
Turn_right
[[0.00783172 0.41742378 0.99579257]]
Turn_right
[[0.00530729 0.33408582 0.9976918 ]]
Turn_right
[[0.00530729 0.33408582 0.9976918 ]]
Turn_right
[[0.00347796 0.4731616  0.9966333 ]]
Turn_right
[[0.00413135 0.5493523  0.99472547]]
Turn_right
[[0.00415355 0.45577738 0.9961954 ]]
Turn_right
[[0.00323328 0.55630934 0.9970438 ]]
Turn_right
[[0.00298554 0.6058581  0.99662673]]
Turn_right
[[0.00401855 0.82354724 0.9882461 ]]
Turn_right
[[0.00143293 0.9825661  0.9427837 ]]
Turn_left
[[8.8471174e-04 9.7355938e-01 9.4869131e-01]]
Turn_left
[[0.0013285  0.95719945 0.96716976]]
Turn_right
[[0.00188762 0.9203023  0.97832525]]
Turn_right
[[0.00188762 0.9203023  0.97832525]]
Turn_right
[[0.00328937 0.77326894 0.9894211 ]]
Turn_right
[[0.00363269 0.16902888 0.9990924 ]]
Turn_right
[[9.1725588e-04 4.7134513e-01 9.9903417e-01]]
Turn_right
[[0.01014712 0.70562816 

[[1.55753195e-02 7.67797232e-04 9.99984205e-01]]
Turn_right
[[1.6366571e-02 7.1141124e-04 9.9998486e-01]]
Turn_right
[[4.4047236e-03 1.7288327e-04 9.9999774e-01]]
Turn_right
[[2.14764476e-03 1.01388454e-04 9.99999285e-01]]
Turn_right
[[2.4853945e-03 1.2797117e-04 9.9999917e-01]]
Turn_right
[[5.6600273e-03 3.6591291e-04 9.9999589e-01]]
Turn_right
[[4.0109158e-03 2.2995472e-04 9.9999785e-01]]
Turn_right
[[4.5923293e-03 1.2534857e-04 9.9999881e-01]]
Turn_right
[[3.4316182e-03 1.5771389e-04 9.9999905e-01]]
Turn_right
[[3.2271743e-03 1.4692545e-04 9.9999905e-01]]
Turn_right
[[3.6141574e-03 1.4767051e-04 9.9999905e-01]]
Turn_right
[[4.1425824e-03 2.1725893e-04 9.9999881e-01]]
Turn_right
[[3.5445690e-03 1.9904971e-04 9.9999911e-01]]
Turn_right
[[4.2463243e-03 2.9388070e-04 9.9999827e-01]]
Turn_right
[[3.5438836e-03 2.7841330e-04 9.9999857e-01]]
Turn_right
[[4.4118464e-03 2.7137995e-04 9.9999845e-01]]
Turn_right
[[3.6712587e-03 3.1992793e-04 9.9999821e-01]]
Turn_right
[[2.7210116e-03 1.3104081

[[1.2763143e-03 5.0168528e-05 1.0000000e+00]]
Turn_right
[[1.5302300e-03 9.5663388e-05 9.9999976e-01]]
Turn_right
[[0.00286448 0.00420642 0.9999815 ]]
Turn_right
[[0.0046238  0.00680512 0.99996436]]
Turn_right
[[0.00215843 0.02295381 0.9999597 ]]
Turn_right
[[0.0028159  0.03238079 0.9999336 ]]
Turn_right
[[1.3541877e-03 7.1331859e-04 9.9999768e-01]]
Turn_right
[[1.3541877e-03 7.1331859e-04 9.9999768e-01]]
Turn_right
[[0.01009074 0.00245205 0.9999501 ]]
Turn_right
[[0.00103509 0.01526043 0.99998116]]
Turn_right
[[0.00167784 0.00736871 0.99998933]]
Turn_right
[[0.00221026 0.00435162 0.99999297]]
Turn_right
[[0.00221026 0.00435162 0.99999297]]
Turn_right
[[0.00311208 0.00118721 0.99999654]]
Turn_right
[[0.00282899 0.00140595 0.9999954 ]]
Turn_right
[[0.00345036 0.00519311 0.9999902 ]]
Turn_right
[[0.00346389 0.00659823 0.99999154]]
Turn_right
[[0.00346389 0.00659823 0.99999154]]
Turn_right
[[0.0014976  0.00225258 0.9999958 ]]
Turn_right
[[0.00582933 0.01279101 0.99992037]]
Turn_right
[[0.

[[6.8484247e-03 4.3085217e-04 9.9999332e-01]]
Turn_right
[[7.9703331e-03 4.3809414e-04 9.9999219e-01]]
Turn_right
[[1.12552345e-02 6.52402639e-04 9.99989808e-01]]
Turn_right
[[1.4977515e-02 4.9954653e-04 9.9999022e-01]]
Turn_right
[[4.3815374e-03 4.9647690e-05 9.9999958e-01]]
Turn_right
[[2.6294291e-03 1.1520519e-05 1.0000000e+00]]
Turn_right
[[5.823821e-03 4.137136e-06 1.000000e+00]]
Turn_right
[[1.1685222e-02 1.0924013e-05 9.9999976e-01]]
Turn_right
[[5.891770e-03 8.586598e-06 1.000000e+00]]
Turn_right
[[1.20661855e-02 1.26212835e-04 9.99996781e-01]]
Turn_right
[[1.4674634e-02 1.7476082e-04 9.9999654e-01]]
Turn_right
[[4.4754148e-03 8.7066379e-05 9.9999917e-01]]
Turn_right
[[3.3555329e-03 1.8903613e-04 9.9999869e-01]]
Turn_right
[[2.6530325e-03 1.7601252e-04 9.9999899e-01]]
Turn_right
[[0.00336564 0.00120699 0.9999882 ]]
Turn_right
[[0.00336686 0.0087907  0.9999827 ]]
Turn_right
[[0.00360519 0.01401973 0.999972  ]]
Turn_right
[[0.00455585 0.02459395 0.99989724]]
Turn_right
[[0.003831

[[0.02767703 0.13796747 0.9945648 ]]
Turn_right
[[0.00705501 0.05785784 0.99979556]]
Turn_right
[[0.0106914  0.08712679 0.9988086 ]]
Turn_right
[[0.00913653 0.17061347 0.9987402 ]]
Turn_right
[[0.0055958  0.07969674 0.99954593]]
Turn_right
[[0.00961956 0.0928252  0.9992104 ]]
Turn_right
[[0.03128773 0.10269707 0.99690974]]
Turn_right
[[0.04851335 0.00827345 0.9989705 ]]
Turn_right
[[0.01326436 0.28089115 0.9984211 ]]
Turn_right
[[0.01395297 0.16217777 0.9987826 ]]
Turn_right
[[0.01395297 0.16217777 0.9987826 ]]
Turn_right
[[0.02228355 0.25238118 0.99630773]]
Turn_right
[[0.02266511 0.2708428  0.9964185 ]]
Turn_right
[[0.01546648 0.15602791 0.99852026]]
Turn_right
[[0.03508398 0.11556354 0.9968543 ]]
Turn_right
[[0.01647449 0.12855244 0.9980813 ]]
Turn_right
[[0.01647449 0.12855244 0.9980813 ]]
Turn_right
[[0.00632602 0.01865658 0.9995196 ]]
Turn_right
[[0.00763112 0.01888677 0.9996103 ]]
Turn_right
[[0.00420925 0.02541402 0.9998982 ]]
Turn_right
[[0.00528434 0.01719275 0.9998493 ]]
Tur

[[0.01182491 0.00236529 0.99988544]]
Turn_right
[[0.01477554 0.00380301 0.99981   ]]
Turn_right
[[0.02311927 0.00626937 0.99956656]]
Turn_right
[[0.02285802 0.00558129 0.99960554]]
Turn_right
[[0.02049702 0.00546336 0.99967086]]
Turn_right
[[0.03626478 0.00318202 0.9994178 ]]
Turn_right
[[0.03942496 0.00275952 0.99944246]]
Turn_right
[[0.04707158 0.00234792 0.99976337]]
Turn_right
[[0.06125852 0.00189182 0.99978256]]
Turn_right
[[0.0565584  0.00145715 0.9997517 ]]
Turn_right
[[3.1923383e-02 5.1379204e-04 9.9986744e-01]]
Turn_right
[[2.1208912e-02 6.7275763e-04 9.9989647e-01]]
Turn_right
[[1.7874181e-02 8.0451369e-04 9.9988830e-01]]
Turn_right
[[1.4441788e-02 6.7254901e-04 9.9991632e-01]]
Turn_right
[[1.3089538e-02 6.4262748e-04 9.9993336e-01]]
Turn_right
[[1.2935162e-02 4.4044852e-04 9.9995863e-01]]
Turn_right
[[1.3227403e-02 5.0684810e-04 9.9995703e-01]]
Turn_right
[[1.2757152e-02 5.5098534e-04 9.9996090e-01]]
Turn_right
[[1.2439132e-02 5.7780743e-04 9.9995780e-01]]
Turn_right
[[9.984

KeyboardInterrupt: 